[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
oft = "4heLVXmupTobMvSAwm8CX9k3N3VFmR2SjV6GpXPVoYRE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./junk-id.json"

[scripts]
test = "npx jest test/anchor"
